### ISSUE TITLE
Aerich migrations

### ISSUE THREAD

**Issue by jpic** [dipdup-io/dipdup#191]
Currently, it seems like we have to drop our database when we change our models:

```
Reindexing required!

Reason: database schema has been modified

Additional context:



You may want to backup database before proceeding. After that perform one of the following actions:

    * Eliminate the cause of reindexing and run `dipdup schema approve`
    * Run `dipdup schema wipe [--immune]` command to drop database and start indexing from scratch
```

Is there not a command like Django's makemigrations to generate migration files?

Are there any plans to integrate aerich migrations?

**Comment by droserasprout** [comment]
Hi, and thanks for reaching out!

aerich is a great tool for database migrations, simple and straightforward. However, I'm not sure if we need to support it officially. It will introduce too much complexity to DipDup, since existing “project migrations” are about changes in code, not data. I haven't tried it yet, but assume you can use aerich as usual, just run `dipdup schema approve --hashes` after every upgrade/downgrade performed with it.

**Comment by droserasprout** [comment]
After a few months, this still seems out-of-scope to me. Closing?
